legacy-um: Drop Label dpmd in /system/product/
This reverts commit 603c011fbddc182dc26e0a2babac2f88b78dd7cf

-log:
FAILED: /out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
/bin/bash -c "(/out/host/linux-x86/bin/checkfc /out/target/product/daisy/obj/ETC/sepolicy_intermediates/sepolicy /out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp ) && (/out/host/linux-x86/bin/sefcontext_compile -o /out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin /out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp )"
libsepol.context_from_record: type vendor_dpmd_exec is not defined
libsepol.context_from_record: could not create context structure
/out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp: line 788 has invalid context u:object_r:vendor_dpmd_exec:s0
libsepol.context_from_record: type vendor_dpmd_exec is not defined
libsepol.context_from_record: could not create context structure
/out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp: line 788 has invalid context u:object_r:vendor_dpmd_exec:s0
Error: could not load context file from /out/target/product/daisy/obj/ETC/file_contexts.bin_intermediates/file_contexts.concat.tmp

Change-Id: a0d48ba97bb92d8971a5d1ef76cb2368651e71c4
Signed-off-by: TogoFire <italomellopereira@gmail.com>